**Q1**

In [2]:
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
print("Array:", arr)
print("a) Add 2:", arr + 2)
print("b) Multiply 3:", arr * 3)
print("c) Divide by 2:", arr / 2)

Array: [10 20 30 40 50]
a) Add 2: [12 22 32 42 52]
b) Multiply 3: [ 30  60  90 120 150]
c) Divide by 2: [ 5. 10. 15. 20. 25.]


**Q2**

In [ ]:
arr = np.array([1, 2, 3, 6, 4, 5])
print("a) Reversed array:", arr[::-1])
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
vals_x, counts_x = np.unique(x, return_counts=True)
most_freq_x = vals_x[np.argmax(counts_x)]
indices_x = np.where(x == most_freq_x)[0]
print("b.i) Most frequent in x is", most_freq_x, "at indices", indices_x)
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
vals_y, counts_y = np.unique(y, return_counts=True)
max_count_y = np.max(counts_y)
most_freq_y = vals_y[counts_y == max_count_y]
indices_y = np.where(np.isin(y, most_freq_y))[0]
print("b.ii) Most frequent in y are", most_freq_y, "at indices", indices_y)

a) Reversed array: [5 4 6 3 2 1]
b i) Most frequent in x is 1 at indices [0 5 7 8 9]
b ii) Most frequent in y are [1 3] at indices [0 1 2 4 8 9]


**Q3**

In [ ]:
arr2 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("a) 1st row, 2nd column:", arr2[0, 1])
print("b) 3rd row, 1st column:", arr2[2, 0])

a) 1st row, 2nd column: 20
b) 3rd row, 1st column: 70


**Q4**

In [ ]:
kushagra = np.linspace(10, 100, 25)
print("Dimensions :", kushagra.ndim)
print("Shape:", kushagra.shape)
print("Size :", kushagra.size)
print("Data type :", kushagra.dtype)
print("Total bytes consumed:", kushagra.nbytes)
transpose = kushagra.reshape(25, 1)
print("\nTranspose :\n", transpose)

Dimensions : 1
Shape: (25,)
Size : 25
Data type : float64
Total bytes consumed: 200

Transpose :
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]


**Q5**

In [3]:
ucs420_kushagra = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35]).reshape(3, 4)
print("Original 3x4 Array:\n", ucs420_kushagra)

print("\nMean:", np.mean(ucs420_kushagra))
print("Median:", np.median(ucs420_kushagra))
print("Max:", np.max(ucs420_kushagra))
print("Min:", np.min(ucs420_kushagra))
print("Unique elements:", np.unique(ucs420_kushagra))

reshaped_ucs420_kushagra = ucs420_kushagra.reshape(4, 3)
print("\nReshaped to 4x3:\n", reshaped_ucs420_kushagra)

resized_ucs420_kushagra = np.resize(ucs420_kushagra, (2, 3))
print("\nResized to 2x3:\n", resized_ucs420_kushagra)

Original 3x4 Array:
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped to 4x3:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized to 2x3:
 [[10 20 30]
 [40 50 60]]
