**Q1**

In [2]:
import numpy as np
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])
temp_corrected = temperature + 2
print("a. Corrected temperatures (+2 deg C):", temp_corrected)
temp_fahrenheit = (9 / 5) * temp_corrected + 32
print("b. Temperatures in Fahrenheit:", temp_fahrenheit)
above_32 = temp_corrected[temp_corrected > 32]
print("c. Readings greater than 32 deg C:", above_32)
count_above_32 = np.sum(temp_corrected > 32)
print("d. Count of readings exceeding 32 deg C:", count_above_32)

# e. Efficiency explanation
print("Vectorization and Boolean indexing execute contiguous operations directly in C-compiled memory blocks.")
print("This eliminates Python interpreter loop overhead, dynamic type-checking, and memory allocation delay.")

a. Corrected temperatures (+2 deg C): [27 30 33 37 40 29 35 42]
b. Temperatures in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
c. Readings greater than 32 deg C: [33 37 40 35 42]
d. Count of readings exceeding 32 deg C: 5
Vectorization and Boolean indexing execute contiguous operations directly in C-compiled memory blocks.
This eliminates Python interpreter loop overhead, dynamic type-checking, and memory allocation delay.


**Q2**

In [4]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])
print("a. Total steps recorded:", np.sum(steps))
print("b. Mean steps:", np.mean(steps))
print("c. Max steps:", np.max(steps), "| Min steps:", np.min(steps))
print("d. Total steps per day (Day 1, Day 2, Day 3):", np.sum(steps, axis=0))
print("e. Total steps per user (User 1 to 4):", np.sum(steps, axis=1))
flat_max_idx = np.argmax(steps)
user_idx, day_idx = np.unravel_index(flat_max_idx, steps.shape)
print("f. Argmax flat index:", flat_max_idx)
print("   Max steps position -> User Index:", user_idx, "(User", user_idx + 1, "), Day Index:", day_idx, "(Day", day_idx + 1, ")")

a. Total steps recorded: 84200
b. Mean steps: 7016.666666666667
c. Max steps: 9500 | Min steps: 4500
d. Total steps per day (Day 1, Day 2, Day 3): [26500 27300 30400]
e. Total steps per user (User 1 to 4): [18300 24500 14400 27000]
f. Argmax flat index: 11
   Max steps position -> User Index: 3 (User 4 ), Day Index: 2 (Day 3 )


**Q3**

In [5]:
original = np.array([1, 2, 3, 4, 5, 6])
print("a. Original array:", original)
subset = original[1:4]
subset[0] = 999
print("c. After modifying subset[0] to 999:")
print("   subset:", subset)
print("   original (affected, since slicing creates a view):", original)
original = np.array([1, 2, 3, 4, 5, 6])
copied_subset = original[1:4].copy()
copied_subset[0] = 500
print("d. After modifying copied_subset[0] to 500:")
print("   copied_subset:", copied_subset)
print("   original (unaffected):", original)
matrix_3x4 = np.arange(1, 13).reshape(3, 4)
print("\ne. 3x4 Matrix:\n", matrix_3x4)
print("f. Extracted Slices:")
print("   - First row:", matrix_3x4[0, :])
print("   - Last row:", matrix_3x4[-1, :])
print("   - Second column:", matrix_3x4[:, 1])
print("   - Rows 1-2 and Columns 2-3:\n", matrix_3x4[1:3, 2:4])
flat_arr = matrix_3x4.flatten()
rav_arr = matrix_3x4.ravel()
rav_arr[0] = 99
print("\nh. Modified ravel()[0] to 99:")
print("   Original 3x4 matrix is affected (ravel creates a view):\n", matrix_3x4)
flat_arr[1] = 88
print("i. Modified flatten()[1] to 88:")
print("   Original 3x4 matrix is unaffected (flatten creates a copy):\n", matrix_3x4)
print("\nj. Attributes of 3x4 Matrix:")
print("   Shape:", matrix_3x4.shape)
print("   Dimensions (ndim):", matrix_3x4.ndim)
print("   Total elements (size):", matrix_3x4.size)
print("   Data type (dtype):", matrix_3x4.dtype)

a. Original array: [1 2 3 4 5 6]
c. After modifying subset[0] to 999:
   subset: [999   3   4]
   original (affected, since slicing creates a view): [  1 999   3   4   5   6]
d. After modifying copied_subset[0] to 500:
   copied_subset: [500   3   4]
   original (unaffected): [1 2 3 4 5 6]

e. 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
f. Extracted Slices:
   - First row: [1 2 3 4]
   - Last row: [ 9 10 11 12]
   - Second column: [ 2  6 10]
   - Rows 1-2 and Columns 2-3:
 [[ 7  8]
 [11 12]]

h. Modified ravel()[0] to 99:
   Original 3x4 matrix is affected (ravel creates a view):
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
i. Modified flatten()[1] to 88:
   Original 3x4 matrix is unaffected (flatten creates a copy):
 [[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

j. Attributes of 3x4 Matrix:
   Shape: (3, 4)
   Dimensions (ndim): 2
   Total elements (size): 12
   Data type (dtype): int64


**Q4**

In [7]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])
y = np.array([40, 65, 30, 85])

print("a. Matrix X - Shape:", X.shape, "| Dimensions:", X.ndim)

X_T = X.T
print("b. X Transposed (X.T):\n", X_T)
print("   Explanation: Transposing swaps rows and columns. X changes from 4 users x 3 features to 3 features x 4 users.")

XTX = X_T @ X
print("\nc. Product X.T @ X:\n", XTX)

XTX_inv = np.linalg.inv(XTX)
print("\nd. Inverse of (X.T @ X):\n", XTX_inv)

beta = XTX_inv @ X_T @ y
print("\ne. Calculated Coefficients (Beta):", beta)

print("\nf. Coefficient Explanation:")
print("   - Beta[0] (Sleep hours):", beta[0], "| Impact of 1 additional hour of sleep on assistance score.")
print("   - Beta[1] (Activity level):", beta[1], "| Impact of 1 unit increase in activity level.")
print("   - Beta[2] (Stress level):", beta[2], "| Impact of 1 unit increase in stress level.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta
print("\ng. New User features [5, 40, 7]:")
print("   Predicted Assistance Score:", predicted_score)

a. Matrix X - Shape: (4, 3) | Dimensions: 2
b. X Transposed (X.T):
 [[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
   Explanation: Transposing swaps rows and columns. X changes from 4 users x 3 features to 3 features x 4 users.

c. Product X.T @ X:
 [[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]

d. Inverse of (X.T @ X):
 [[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]

e. Calculated Coefficients (Beta): [-0.15921454  0.14083853 10.06302242]

f. Coefficient Explanation:
   - Beta[0] (Sleep hours): -0.1592145415946895 | Impact of 1 additional hour of sleep on assistance score.
   - Beta[1] (Activity level): 0.14083852991906243 | Impact of 1 unit increase in activity level.
   - Beta[2] (Stress level): 10.063022422714587 | Impact of 1 unit increase in stress level.

g. New User features [5, 40, 7]:
   Predicted Assistance Score: 75.27862544779117
